Chroy.Web/Models/ErrorViewModel.cs
using System;

namespace Chroy.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Chroy.Web/Areas/Admin/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChRoy.Repository;
using Microsoft.AspNetCore.Mvc;

namespace Chroy.Web.Areas.Admin.Controllers
{
	[Area("Admin")]
    public class BaseController : Controller
    {
		
    }
}

Chroy.Web/Areas/Admin/Controllers/BillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ChRoy.Repository;

namespace Chroy.Web.Areas.Admin.Controllers
{
    public class BillController : BaseController
	{
		private MyDbContext db;
		public BillController(MyDbContext _context)
		{
			db = _context;
		}

        // GET: Bill
        public ActionResult Index()
        {
            return View();
        }

		[HttpGet]
		public IActionResult Get()
		{
			var list = db.Bills.ToList();

			return Json(list);
		}

		// GET: Bill/Details/5
		public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Bill/Create
        public ActionResult Create()
        {


            return View();
        }

        // POST: Bill/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Bill/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Bill/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Bill/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Bill/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Chroy.Web/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChRoy.Repository;
using Microsoft.AspNetCore.Mvc;

namespace Chroy.Web.Areas.Admin.Controllers
{
    public class CategoryController : BaseController
	{
		private MyDbContext db;
		public CategoryController(MyDbContext _context)
		{
			db = _context;
		}

		public IActionResult Index()
        {
            return View();
        }

		public IActionResult Get()
		{
			var list = db.Categories.ToList();

			return Json(list);
		}
    }
}

Chroy.Web/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ChRoy.Repository;

namespace Chroy.Web.Areas.Admin.Controllers
{
	public class HomeController : BaseController
	{
		private MyDbContext db;
		public HomeController(MyDbContext _context)
		{
			db = _context;
		}

		public IActionResult Index()
		{
			return View();
		}
	}
}

Chroy.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Chroy.Web.Models;

namespace Chroy.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Chroy.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChRoy.Repository;
using ChRoy.Service;
using Microsoft.AspNetCore.Mvc;

namespace Chroy.Web.Controllers
{
	public class UserController : Controller
	{
		private readonly UserService us;
		public UserController(UserService Context)
		{
			us = Context;
		}

		public IActionResult Index()
		{
			var list = us.GetLists().ToList();

			return View(list);
		}

		public IActionResult Add()
		{
			var user = new User();

			return View(user);
		}

		[HttpPost]
		public IActionResult AddSubmit(User user)
		{
			//db.Uesrs.Add(user);

			//db.SaveChanges();
			us.AddUser(user);

			TempData["msg"] = "添加成功";

			return View("Add", user);
		}

	}
}

Chroy.Web/Areas/Admin/Views/Category/Index.cshtml
@{
	Layout = null;
}

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Index</title>
	<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
	<script src="~/lib/vue/vue.min.js"></script>
	<script src="~/lib/axios/axios.min.js"></script>
</head>
<body>
	<div id="app">
		<button class="btn-default">添加</button>

		<table v-if="categoryList.length > 0" class="table-condensed" border="1">
			<thead class="navbar-header">
				<tr>
					<th>编号</th>
					<th>科目名称</th>
					<th></th>
				</tr>
				<tr v-for="(contact,index) in categoryList">
					<td><input type="text" v-model="contact.CategoryID" /></td>
					<td><input type="text" v-model="contact.CategoryName" /></td>
					<td></td>
				</tr>
			</thead>
		</table>
	</div>
	<script>
		var vm = new Vue({
			el: "#app",
			data: {
				categoryList: []
			},
			mounted() {
				this.getAllCategory();
			},
			methods: {
				getAllCategory: function () {
					axios.get('@Url.Action("Get", "Category")'
                    ).then(
                        (response) => {
							this.categoryList = [];
                            for (var i = 0; i < response.data.length; i++) {
								this.categoryList.push(response.data[i]);
                            }

                        },
                        (response) => {
                            alert(response.status);
                        }
                    ).catch(function (response) {
                        alert(response);
                    });
				}
			}
		});
	</script>
</body>
</html>

Chroy.Web/Areas/Admin/Views/Home/Index.cshtml
@{
	Layout = null;
}

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Index</title>
	<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
	<script src="~/lib/vue/vue.min.js"></script>
	<script src="~/lib/axios/axios.min.js"></script>
</head>
<body>
	<div id="app">
		<table v-if="billsList.length > 0" class="table-condensed" border="1">
			<thead class="navbar-header">
				<tr>
					<th>编号</th>
					<th>账户</th>
					<th>科目</th>
					<th>摘要</th>
					<th>金额</th>
					<th>备注</th>
					<th></th>
				</tr>
				<tr v-for="(contact,index) in billsList">
					<td><input type="text" v-model="contact.BillID" /></td>
					<td><input type="text" v-model="contact.AccountName" /></td>
					<td><input type="text" v-model="contact.CategoryName" /></td>
					<td><input type="text" v-model="contact.Remark" /></td>
					<td><input type="text" v-model="contact.Amount" /></td>
					<td><input type="text" v-model="contact.Description" /></td>
					<td>
					</td>
				</tr>
			</thead>
		</table>
	</div>
	<script>
		var vm = new Vue({
			el: "#app",
			data: {
				billsList: []
			},
			mounted() {
				this.getAllBills();
			},
			methods: {
				getAllBills: function () {
					axios.get('@Url.Action("Get", "Bill")'
                    ).then(
                        (response) => {
							this.billsList = [];
                            for (var i = 0; i < response.data.length; i++) {
								this.billsList.push(response.data[i]);
                            }
							
                        },
                        (response) => {
                            alert(response.status);
                        }
                    ).catch(function (response) {
                        alert(response);
                    });
				}
			}
		});
	</script>
</body>
</html>

Chroy.Web/Areas/Admin/Views/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_AdminLayout</title>
</head>
<body>
</body>
</html>

Chroy.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Chroy.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Chroy.Web/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Chroy";
}

<main role="main" class="inner cover">
	<h1 class="cover-heading">ChRoy®</h1>
	@*<div class="lead" style="margin-bottom: 2rem;">
		GUARANTEED DESIGN SINCE 1972
	</div>
	<div class="lead">
		Telefono: <a href="tel:+0393349065896">+039 3349065896</a>
	</div>*@
</main>

Chroy.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Chroy.it</title>

	@*<environment include="Development">
			<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
			<link rel="stylesheet" href="~/css/site.css" />
		</environment>
		<environment exclude="Development">
			<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
				  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
				  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
			<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
		</environment>*@
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="icon" href="favicon.png">

	<title>chroy</title>

	<!-- Bootstrap core CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

	<!-- Custom styles for this template -->
	<link href="~/css/cover.css" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">

</head>
<body class="text-center">
	<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
		<header class="masthead mb-auto">
			<div class="inner">

			</div>
		</header>
		@RenderBody()
		<footer class="mastfoot mt-auto">
			<div class="inner">
				&copy; 2018 - Chroy.It CAIQIANLIANG & DAICHENGCHENG
			</div>
		</footer>
	</div>

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

	@RenderSection("Scripts", required: false)
</body>
</html>

Chroy.Web/Views/User/Add.cshtml
@model ChRoy.Repository.User
@{
	Layout = null;
}

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Add</title>
</head>
<body>
	<p style="color:red;">@TempData["msg"]</p>

	@using (Html.BeginForm("addsubmit", "user"))
	{
		@Html.LabelFor(m => m.UserName)
		@Html.TextBoxFor(m => m.UserName)
		@Html.LabelFor(m => m.Password)
		@Html.PasswordFor(m => m.Password)

		@Html.AntiForgeryToken();

		<button type="submit">提  交</button>
	}

	<a href="/user/index">返回</a>
</body>
</html>

Chroy.Web/Views/User/Index.cshtml
@model List<ChRoy.Repository.User>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
	<a href="/user/add">新增</a>
	<ul>
		@foreach (var item in Model)
		{
			<li>@item.UserName</li>
		}
	</ul>
</body>
</html>